services:
  database:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - redis-data:/data
    restart: unless-stopped

  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: production
    container_name: api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
      - redis
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - api
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    container_name: ollama
    pull_policy: always
    tty: true
    command: "serve & sleep 10 && ollama run qwen2:7b"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_DEBUG=false

volumes:
  postgres-data:
  redis-data:
  ollama:
